### ISSUE TITLE
Unrealistic water effect around block above water

### ISSUE THREAD

**Issue by Macintosh-Fan** [DeDelner/projectLUMA-issues#25]
Hello. I get this weird water warp effect thing when I am looking at blocks near or above water.

<img width="1512" alt="Screen Shot 2022-03-25 at 2 50 36 PM" src="https://user-images.githubusercontent.com/50642934/160207313-1a773b3c-0df6-4c27-b53e-39844ea28ce5.png">

**Comment by WoMspace** [comment]
It's an artefact from the way that the refractions in the water are done. If you turn off refractions they'll go away. There's nothing* that can be done about them.
*technically there are but it's not something DeDelner is going to do because it's very complex

**Comment by Macintosh-Fan** [comment]
I see. I'll just close the issue.
